name: 'Set Expo build numbers'
description: 'Sets the version, buildNumber and versionCode in app.json'
author: 'Sina Khelil'
outputs:
  version:
    description: The version number in expo app.json
  versioncode:
    description: The set Android versioncode
  buildnumber:
    description: The set iOS buildnumber
inputs:
  filepath: # change this
    required: false
    description: 'Path to app.json'
    default: './app.json'
  platforms: # change this
    required: false
    description: 'Comma-separated list of platforms (iOS and Android available)'
    default: 'ios,android'
  tag: # change this
    required: true
    description: 'The tag to use for the version number'
    default: 'v1.0.0'
runs:
  using: 'node12'
  main: 'dist/index.js'
